
services:
  database:
    container_name: database
    image: mysql
    environment:
      MYSQL_DATABASE: importTest
      MYSQL_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      - stocks-app
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - database_data:/var/lib/mysql

  nginx:
    container_name: nginx
    image: nginx:1.18-alpine
    command: ["/usr/sbin/nginx"]
    networks:
      - stocks-app
    ports:
      - "8001:8080"
    expose:
      - 8080
      - 8081
    volumes:
      - .:/var/www/html:cached
      - ./docker/conf/nginx.conf:/etc/nginx/nginx.conf
      - app_fpm:/sock

  app:
    container_name: app
    build:
      context: .
    command: ["php-fpm"]
    environment:
      XDEBUG_CONFIG: "idekey=stocks-app client_host=host.docker.internal"
      XDEBUG_MODE: debug
      XDEBUG_TRIGGER: 1
    networks:
      - stocks-app
    volumes:
      - ./docker/conf/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - .:/var/www/html:cached
      - app_fpm:/sock



volumes:
  database_data:
  app_fpm:

networks:
  stocks-app:
    driver: bridge